version: '3.8'
services:
  nginx:
    build:
      context: .
      dockerfile: nginx.Dockerfile
    ports:
      - "81:81"
    volumes:
      - static_volume:/app/hotel_booking/staticfiles:ro
      - media_volume:/app/media:ro
    depends_on:
      - web
    restart: unless-stopped
    networks:
      - app-network

  web:
    container_name: api_web_1
    build: .
    entrypoint: ["/app/entrypoint.sh"]
    working_dir: /app/hotel_booking
    volumes:
      - static_volume:/app/hotel_booking/staticfiles
      - media_volume:/app/media
      - logs_volume:/app/logs
      - ./entrypoint.sh:/app/entrypoint.sh
      - .:/app:cached
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=hotel_booking.deployment
      - DJANGO_SUPERUSER_USERNAME=${DJANGO_SUPERUSER_USERNAME}
      - DJANGO_SUPERUSER_EMAIL=${DJANGO_SUPERUSER_EMAIL}
      - DJANGO_SUPERUSER_PASSWORD=${DJANGO_SUPERUSER_PASSWORD}
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - app-network

  db:
    container_name: api_db_1
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - app-network

volumes:
  postgres_data:
  static_volume:
  media_volume:
  logs_volume:

networks:
  app-network:
    driver: bridge
