# Generated by Django 5.2.3 on 2025-07-23 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_options_customuser_address_line_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='marketing_emails',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='loyalty_points',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='loyalty_tier',
        ),
    ]
